git clone https://github.com/vim-scripts/Align.git
git clone https://github.com/HonkW93/automatic-verilog.git
git clone https://github.com/Yggdroot/indentLine.git
git clone https://github.com/preservim/nerdcommenter.git
git clone https://github.com/preservim/nerdtree.git
git clone https://github.com/luochen1990/rainbow.git
git clone https://github.com/preservim/tagbar.git
git clone https://github.com/yegappan/taglist.git
git clone https://github.com/junegunn/vim-plug.git
git clone https://github.com/vim-scripts/vlog_inst_gen.git
git clone https://github.com/VundleVim/Vundle.vim.git
git clone https://github.com/altercation/vim-colors-solarized.git 
git clone https://github.com/vim-airline/vim-airline.git 
git clone https://github.com/nachumk/systemverilog.vim.git
git clone https://github.com/zhuzhzh/verilog_emacsauto.vim.git
git clone https://github.com/veripool/verilog-mode.git
git clone git@github.com:vhda/verilog_systemverilog.vim.git
git clone https://github.com/WeiChungWu/vim-SystemVerilog.git
git clone git@github.com:airblade/vim-gitgutter.git
